"""
PRAHARI · object storage
════════════════════════════════════════════════════════════════════════════
Image bytes do not belong in PostgreSQL. The database stores a key and the
metadata; the bytes live in object storage.

    LocalStorage   a directory. Correct for development and a single-box demo.
    S3Storage      S3 or any S3-compatible endpoint (Cloudflare R2, MinIO,
                   Backblaze B2), with presigned GETs so image URLs expire.

Uploads are validated before anything is written: real image bytes decoded by
Pillow, a size cap, a content-type derived from the DECODED image rather than
from the client's filename, and a generated key. A client-supplied filename is
never used for anything.
"""
from __future__ import annotations

import hashlib
import io
import logging
import uuid
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any

from .config import Settings, get_settings
from .errors import bad_request, too_large

log = logging.getLogger("prahari.storage")

ALLOWED_FORMATS = {"JPEG": "image/jpeg", "PNG": "image/png", "WEBP": "image/webp"}
MAX_DIMENSION = 4096
THUMB = (480, 480)


class StoredObject(dict):
    pass


class Storage(ABC):
    name = "abstract"

    @abstractmethod
    def put(self, key: str, data: bytes, content_type: str) -> str: ...

    @abstractmethod
    def url(self, key: str) -> str: ...

    @abstractmethod
    def get(self, key: str) -> bytes: ...

    def health(self) -> dict[str, Any]:
        return {"provider": self.name, "ok": True}


class LocalStorage(Storage):
    name = "local"

    def __init__(self, settings: Settings):
        self.root = Path(settings.storage_local_dir).resolve()
        self.root.mkdir(parents=True, exist_ok=True)
        self.public_base = settings.storage_public_base.rstrip("/")

    def _path(self, key: str) -> Path:
        # Keys are generated by this module, never client-supplied, but the
        # containment check stays because "never" is a claim about today's code.
        p = (self.root / key).resolve()
        if not str(p).startswith(str(self.root)):
            raise bad_request("bad_storage_key", "Invalid storage key.")
        return p

    def put(self, key, data, content_type):
        p = self._path(key)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)
        return key

    def get(self, key):
        return self._path(key).read_bytes()

    def url(self, key):
        return f"{self.public_base}/{key}"

    def health(self):
        try:
            probe = self.root / ".healthcheck"
            probe.write_text("ok")
            probe.unlink(missing_ok=True)
            return {"provider": "local", "ok": True, "dir": str(self.root)}
        except Exception as exc:                          # pragma: no cover - infra
            return {"provider": "local", "ok": False, "error": str(exc)[:160]}


class S3Storage(Storage):
    name = "s3"

    def __init__(self, settings: Settings):
        self.s = settings
        import boto3  # imported lazily
        self.client = boto3.client(
            "s3", endpoint_url=settings.s3_endpoint_url,
            region_name=settings.s3_region,
            aws_access_key_id=settings.s3_access_key,
            aws_secret_access_key=settings.s3_secret_key)
        self.bucket = settings.s3_bucket

    def put(self, key, data, content_type):
        self.client.put_object(Bucket=self.bucket, Key=key, Body=data,
                               ContentType=content_type,
                               CacheControl="private, max-age=3600")
        return key

    def get(self, key):
        return self.client.get_object(Bucket=self.bucket, Key=key)["Body"].read()

    def url(self, key):
        return self.client.generate_presigned_url(
            "get_object", Params={"Bucket": self.bucket, "Key": key},
            ExpiresIn=self.s.signed_url_ttl_seconds)

    def health(self):
        try:
            self.client.head_bucket(Bucket=self.bucket)
            return {"provider": "s3", "ok": True, "bucket": self.bucket}
        except Exception as exc:                          # pragma: no cover - infra
            return {"provider": "s3", "ok": False, "error": str(exc)[:160]}


def build_storage(settings: Settings | None = None) -> Storage:
    s = settings or get_settings()
    if s.storage_provider == "s3":
        if not (s.s3_bucket and s.s3_access_key and s.s3_secret_key):
            raise RuntimeError("STORAGE_PROVIDER=s3 requires S3_BUCKET, S3_ACCESS_KEY, S3_SECRET_KEY")
        return S3Storage(s)
    return LocalStorage(s)


# ── validation and derivatives ──────────────────────────────────────────────
def validate_image(data: bytes, max_bytes: int) -> tuple[str, int, int, str]:
    """Returns (content_type, width, height, normalised_format).

    The content type comes from what Pillow actually decoded, not from the
    upload's declared type or filename. An uploaded file is never executed,
    never stored under its own name, and never trusted to describe itself.
    """
    if not data:
        raise bad_request("empty_upload", "The uploaded file is empty.")
    if len(data) > max_bytes:
        raise too_large(max_bytes)
    from PIL import Image
    try:
        with Image.open(io.BytesIO(data)) as probe:
            fmt = (probe.format or "").upper()
            probe.verify()
    except Exception:
        raise bad_request("not_an_image",
                          "That file is not a readable image. Upload a JPEG or PNG photograph.",
                          message_mr="ही फाइल वाचता येणारा फोटो नाही. JPEG किंवा PNG फोटो टाका.") from None
    if fmt not in ALLOWED_FORMATS:
        raise bad_request("unsupported_image_format",
                          f"{fmt or 'That format'} is not supported. Use JPEG, PNG or WebP.")
    with Image.open(io.BytesIO(data)) as img:
        w, h = img.size
    if w > MAX_DIMENSION or h > MAX_DIMENSION:
        raise bad_request("image_too_large_dimensions",
                          f"Image is {w}×{h}px. The limit is {MAX_DIMENSION}px per side.")
    if w < 64 or h < 64:
        raise bad_request("image_too_small",
                          "That image is too small to analyse. Take the photograph again.")
    return ALLOWED_FORMATS[fmt], w, h, fmt


def sanitize(data: bytes) -> bytes:
    """Re-encode through Pillow. This strips EXIF — which carries the GPS
    coordinates of a farmer's home — and any payload smuggled in a metadata
    segment. The stored image is bytes this process wrote, not bytes a client
    sent."""
    from PIL import Image
    with Image.open(io.BytesIO(data)) as img:
        img = img.convert("RGB")
        out = io.BytesIO()
        img.save(out, format="JPEG", quality=88, optimize=True)
        return out.getvalue()


def thumbnail(data: bytes) -> bytes:
    from PIL import Image
    with Image.open(io.BytesIO(data)) as img:
        img = img.convert("RGB")
        img.thumbnail(THUMB)
        out = io.BytesIO()
        img.save(out, format="JPEG", quality=80, optimize=True)
        return out.getvalue()


def make_key(prefix: str, ext: str = "jpg") -> str:
    u = uuid.uuid4().hex
    return f"{prefix}/{u[:2]}/{u}.{ext}"


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()
